### ISSUE TITLE
BPF and pure-lua pipelines diverge on portrange N-M, M<N

### ISSUE THREAD

**Issue by kbara** [Igalia/pflua#129]
Using time as seed: 34695539
The property was falsified.
The pflang expression was portrange 49577-19673 and the packet number 938
Rerun as: pflua-quickcheck --seed=34695539 --iterations=5 properties/pflua_pipelines_match data/wingolog.pcap

**Comment by andywingo** [comment]
What is the meaning of portrange 49577-19673 ? :)

**Comment by kbara** [comment]
It's the same as portrange 19673-49577 in tcpdump (the output of tcpdump -d is identical for both).

**Comment by kbara** [comment]
Fixed with 0a2e824049e1b4dc25c4210a5f9ebafe01a95fbd
