### ISSUE TITLE
Possibly vestigial make targets have bitrotted

### ISSUE THREAD

**Issue by kbara** [Igalia/pflua#155]
In src/Makefile, test:, test_jit_off:, and trace: have all bitrotted. Should they be fixed or removed? @dpino @andywingo

**Comment by dpino** [comment]
It seems this code is from when @jmunhoz was working in the benchmarking. If we haven't run these makes in the last months I believe is because they're no longer needed. I'd remove them.

**Comment by kbara** [comment]
Ok, cool. I've submitted a PR to remove them; it's not like they'd be hard to re-add if we did need them, but it looks like we don't.

**Comment by kbara** [comment]
The PR was merged and closed, so this should be too.
