### ISSUE TITLE
Pflua accepts statements like "len < 1^1", which are not in libpcap's pflang

### ISSUE THREAD

**Issue by kbara** [Igalia/pflua#201]
Tcpdump bails out:
```
tcpdump -d "len < 1 ^ 1"
tcpdump: illegal token: ^
```

Pflua happily compiles the invalid pflang:
```
./pflua-compile "len < 1^1"
return function(P,length)
   return length < 0
end
```

This appears to be a minor issue. Pflua has a small feature that libpcap doesn't. Unless it causes a compatibility problem beyond pflua accepting statements libpcap won't, a wontfix resolution seems reasonable.

**Comment by andywingo** [comment]
Why is this invalid for libpcap?  I don't understand :)

**Comment by andywingo** [comment]
wingo@rusty:~/src/guile$ /usr/sbin/tcpdump --help -d 'len < 1^1'
tcpdump version 4.6.2
libpcap version 1.6.2
OpenSSL 1.0.2a 19 Mar 2015
Usage: tcpdump [-aAbdDefhHIJKlLnNOpqRStuUvxX#] [ -B size ] [ -c count ]
		[ -C file_size ] [ -E algo:secret ] [ -F file ] [ -G seconds ]
		[ -i interface ] [ -j tstamptype ] [ -M secret ] [ --number ]
		[ -Q in|out|inout ]
		[ -r file ] [ -s snaplen ] [ --time-stamp-precision precision ]
		[ -T type ] [ --version ] [ -V file ]
		[ -w file ] [ -W filecount ] [ -y datalinktype ] [ -z command ]
		[ -Z user ] [ expression ]
wingo@rusty:~/src/guile$ sudo /usr/sbin/tcpdump -d 'len < 1^1'
(000) ld       #pktlen
(001) jge      #0x0             jt 2	jf 3
(002) ret      #0
(003) ret      #262144

**Comment by kbara** [comment]
Interesting. My test case was with:
tcpdump version 4.5.1
libpcap version 1.5.3

**Comment by kbara** [comment]
I've marked this invalid and wontfix, as the newer version of libpcap that you tested on has this feature.
