### ISSUE TITLE
Doesn’t make pflua

### ISSUE THREAD

**Issue by 9Demien9** [Igalia/pflua#267]
Hello!
Doesn’t make pflua.
Tested on archlinux and Debian 11.
../tools/dump-markdown "ether[&tcp[0]] = tcp[0]" > tcp-address.md.tmp && mv tcp-address.md.tmp tcp-address.md
pcap_compile failed!: can't parse filter expression: syntax error
pcap_compile failed!: can't parse filter expression: syntax error

**Comment by dpino** [comment]
Your expression doesn't seem to be correct. `tcpdump` can't either parse the same expression:

```
$ tcpdump "ether[&tcp[0]] = tcp[0]"
tcpdump: can't parse filter expression: syntax error
```
