### ISSUE TITLE
optimize.lua:58: table index is NaN

### ISSUE THREAD

**Issue by kbara** [Igalia/pflua#63]
This is reproduced about one per 3000-5000 quickcheck runs. It's reminiscent of a problem we saw in Spain, with range-checking length. Did some of the patches from that not make it to the tree? I notice pflua-quickcheck doesn't have the notes on how to rerun it (with the number of iterations, etc), either.

./pflua-quickcheck savefiles/wingolog.org.pcap
Using time as seed: 450120872
luajit: deps/pflua/src/pf/optimize.lua:58: table index is NaN
stack traceback:
        deps/pflua/src/pf/optimize.lua:58: in function 'cfkey'
        deps/pflua/src/pf/optimize.lua:69: in function 'f'
        deps/pflua/src/pf/optimize.lua:57: in function 'cfkey'
        deps/pflua/src/pf/optimize.lua:408: in function 'lookup'
        deps/pflua/src/pf/optimize.lua:577: in function 'visit'
        deps/pflua/src/pf/optimize.lua:580: in function 'visit'
        deps/pflua/src/pf/optimize.lua:595: in function 'visit'
        deps/pflua/src/pf/optimize.lua:580: in function 'visit'
        deps/pflua/src/pf/optimize.lua:595: in function 'visit'
        deps/pflua/src/pf/optimize.lua:503: in function 'visit'
        deps/pflua/src/pf/optimize.lua:537: in function 'visit'
        deps/pflua/src/pf/optimize.lua:541: in function 'visit'
        deps/pflua/src/pf/optimize.lua:541: in function 'visit'
        deps/pflua/src/pf/optimize.lua:541: in function 'visit'
        deps/pflua/src/pf/optimize.lua:541: in function 'infer_ranges'
        deps/pflua/src/pf/optimize.lua:689: in function 'f'
        deps/pflua/src/pf/optimize.lua:682: in function 'fixpoint'
        deps/pflua/src/pf/optimize.lua:696: in function 'optimize'
        ./pflua-quickcheck:123: in function 'main'
        ./pflua-quickcheck:144: in main chunk
        [C]: at 0x00404bc0

**Comment by andywingo** [comment]
This was fixed in #116.
