### ISSUE TITLE
Pflua: large multiplications use floats, leading to different results

### ISSUE THREAD

**Issue by kbara** [Igalia/pflua#83]
Filter: len < 405434949 * 1881196573

Tcpdump compares len with: 1588910545
Pflua compares len with: 1588910592

Tcpdump is using the 32-bit register with the low bits of the result from imull, with integer operands.
Pflua is, like typical Lua, using doubles, and the result is large enough that it's in a range where only some integers can be represented.

This particular example is somewhat contrived (len only has a 16-bit range, so both are trivially true), but for some pairs of numbers, the low 32 bits differing and being under 2^16 could lead to different results with len. More generally, in non-len expressions, this is occasionally problematic.

To solve this, we need to use integer multiplication.

**Comment by kbara** [comment]
We can force integer multiplication quite easily, by using LL.
% luajit
LuaJIT 2.0.3 -- Copyright (C) 2005-2014 Mike Pall. http://luajit.org/
JIT: ON CMOV SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> print((2^53 + 1LL) % 2)
1LL
> print((2^53 + 1) % 2)
0

**Comment by andywingo** [comment]
A full solution needs to discard high bits, and return a normal Lua number, not a LL number.  Can you work that up? :)

**Comment by kbara** [comment]
That's just a % (2^32) and a call to tonumber(), I believe. :)

**Comment by andywingo** [comment]
You'll also need to force one of the arguments to be an LL number.

**Comment by kbara** [comment]
Yes. And I'll need to make sure > 2^31 numbers are forced to negative, as well.

**Comment by kbara** [comment]
A normal number [any math op] an LL number is an LL number, so forcing LL is straightforward.

**Comment by andywingo** [comment]
why would you need to make sure numbers greater than 2^31 are negative?  pflang numbers are unsigned.

**Comment by kbara** [comment]
Perhaps numbers > 2^31 don't need to be negative; I need to think that through more carefully. Here's the line of thought that made me think it needs to be thought about:

Pflang numbers are unsigned, but they take advantage of 2s-complement arithmetic fairly extensively, as far as I can tell. You can have negative numbers as arguments and they do what you'd expect:
% tcpdump -d "len < 4 + -1"
(000) ld       #pktlen
(001) jge      #0x3             jt 2    jf 3

-1 is treated as a positive number, 2^32 - 1, and working with 32-bit ints, that's fine; the results for addition and subtraction are identical, and so is multiplication is the low 32 bits (and the high 32 are discarded). Semantics do diverge for division (0xffffffff / 2 is 0 with signed division, and 7fffffff with unsigned division), and pflang uses the unsigned division semantics, as expected.

The problem here is extensive punning that fairly convincingly supports what looks like negative numbers while relying on 32-bit unsigned ints. We have Lua numbers (doubles), and 64 bit ints (with LL and cdata), and we're trying to preserve semantics while our underlying representations are different and the puns don't work on the types we're actually using, but can be faked with careful thought.

**Comment by andywingo** [comment]
Arguments to arithmetic operators in the IR of pflua always start by being in uint32 range, if necessary by the inclusion of uint32() calls.  For that reason the operands to * will be in the uint32 range, and we don't need to do anything special in the implementation of LL*.

**Comment by andywingo** [comment]
Fixed in #109, I think, though the optimization to lower '*64' to '*' isn't yet in place.
